services:
  db:
    image: postgres:16
    container_name: tcss460-group-2-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tcss460
    volumes:
      - tcss460_pgdata:/var/lib/postgresql/data

volumes:
  tcss460_pgdata:
